disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "kvg.dev"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = ""
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"


